index.html, update.json
=> bump 3.2.1 to notify users

index.html, update.json
=> bump 3.2.5

index.html, support.html, template/head.tpl
This would save a HTTP redirect
=> remove www from twitter url (Not needed)

docs/api.html, docs/configuration.html, docs/contributions.html, docs/css/app.css, docs/docker.html, docs/faq.html, docs/index.html, docs/installation.html, docs/keyboard.html, docs/md/api.md, docs/md/configuration.md, docs/md/faq.md, docs/md/installation.md, docs/md/keyboard.md, docs/md/node.md, docs/md/read-more.md, docs/md/settings.md, docs/md/structure.md, docs/md/update.md, docs/md/upgrade.md, docs/node.html, docs/read-more.html, docs/releases.html, docs/settings.html, docs/structure.html, docs/template/frame.html, docs/update.html, docs/upgrade.html
Separates the ToC from the content a little. Subjective. @ildyria can decide if he prefers it!
=> Add <hr> between ToC and content

README.md
Add setup section to README.md
Thank you :)
=> Add setup section

docs/md/node.md, docs/node.html
This PR is part of https://github.com/LycheeOrg/Lychee-front/pull/215
The front-end Node.js require version were changed when PR https://github.com/LycheeOrg/Lychee-front/pull/215
Thank you :)
=> docs: nodejs v10.0.0 or later

docs/api.html, docs/configuration.html, docs/contributions.html, docs/distributions.html, docs/docker.html, docs/faq.html, docs/index.html, docs/installation.html, docs/md/installation.md, docs/md/upgrade.md, docs/node.html, docs/releases.html, docs/structure.html, docs/update.html, docs/upgrade.html
=> Update installation and upgrade pages, including a more complete nginx configuration example

.github/workflows/CI.yml, .travis.yml, docs/faq.html, docs/md/faq.md, gen.py, makefile
Adding information on how to edit **ImageMagick** settings to allow uploading images with larger resolutions.
=> Update FAQ Section on Uploading Large Images

README.md, docs/md/update.md, docs/update.html, index.html, support.html, update.json
The title is pretty self explanatory, I just added `gitpython` to the `pip3` dependencies listed in README.md, and also added a small precision for SQLite users, as one had an issue due to this imprecision.
I'm open for discussion, as always, and I'd be glad to have feedback.
Should fix LycheeOrg/Lychee#1002
=> Added gitpython to pip3 dependencies in README, and a precision for manual upgrade for SQLite users

docs/upgrade.md
/etc/apache2/site-available/->/etc/apache2/sites-available
=> Docs: small typo on /upgrade.html

docs/releases.md
Add CVE info for old version v3.2.16
=> Add CVE info for old version v3.2.16

docs/installation.md
- Path to installation directory adapted to Installation instruction from Master branch
- php-version updated
=> nginx-config adapted

.gitignore, docs/distributions.md
Just group the 3 external Lychee distributions.
=> Doc distrib

docs/releases.md
Add changelogs prior v2.0 to have a completed list of them, taken from https://github.com/electerious/Lychee/tags.
=> Complete changelogs

docs/faq.md
Closes https://github.com/LycheeOrg/Lychee/issues/1613
=> Fix hide smart albums CSS

docs/configuration.md
This PR adds documentation about the Unix socket options for Redis.
=> Add documentation for Unix socket options for Redis

docs/configuration.md
This PR add documentation for the authentication guard option.
=> Add documentation for authentication guard option

docs/releases.md
Add v4.7.1 to release notes.
Add v4.7.2 to release notes.
Add v4.7.3 to release notes.
=> version 4.7.3

docs/advanced-setups.md
I'm proposing to add documentation for Object Storage to `advanced-setups.md`
=> Object Storage documentation

docs/advanced-setups.md
=> Fix advanced installation page.

docs/releases.md
Should have been published months ago...
=> version 4.13.0

docs/installation.md, docs/releases.md
=> version 5.0.0

docs/installation.md, docs/update.md
As discussed in https://github.com/LycheeOrg/Lychee/issues/2104
=> Updating documentation to reflect 5.0.0 changes in build steps

src/content/post/2024-12-13-what-is-next.mdx, src/pages/get-supporter-edition.astro
=> What is next?

docs/external_tracking.md
add doc to configure medama web analytics
=> feat(analytics): add doc to configure medama web analytics

.github/workflows/Docker.yml, Dockerfile, README.md, makefile, src/components/widgets/Content3.astro, src/config.yaml, src/navigation.js, src/pages/index.astro, template/doc-frame.html
~~Will be useful later to host the website on docker compose...~~
Now live at https://lycheeorg.dev
=> Use docker to build instead

docs/releases.md
=> Fix release notes

src/navigation.js
=> Add release notes in footer

docs/configuration.md
I added the S3 variables to the config docs under AWS and explained them
=> Expand on AWS env variables 
